### ISSUE TITLE
 Error: Unknown variable dynamic import Unable to install Supabase on SvelteKit

### ISSUE THREAD

**Issue by iqcudi** [joshnuss/svelte-supabase#3]
Hello, I am running into this error while trying to install supabase on sveltekit. Anyone can help please? thank you in advance

![image](https://user-images.githubusercontent.com/73866390/115975138-d0c7e180-a527-11eb-81fa-f5aadd3911e6.png)

**Comment by Pixselve** [comment]
Can you give us some steps to reproduce the issue ?
I just tried with a fresh installation of SvelteKit and it worked fine.

**Comment by RiadhKHEDHIRI** [comment]
> 
> 
> Can you give us some steps to reproduce the issue ?
> I just tried with a fresh installation of SvelteKit and it worked fine.

I encountered the same issue with a fresh SvelteKit installation as of today. I am using NPM 7.

**Comment by avoinicu** [comment]
Seems like it has to do with the latest version of `svelte-add`.

Running this did the trick for me:
```
 $ npx svelte-add@2021.4.1-9.0 joshnuss/svelte-supabase
```

**Comment by joshnuss** [comment]
Looks like `svelte-add` changed what is expected to be defined in an adder: https://github.com/svelte-add/svelte-add/commit/cd6c1bf84b656d941d56a1aa3f04dbd5dd41c30a

There is an issue open here: https://github.com/svelte-add/svelte-add/issues/26

For now, @avoinicu's solution is the way to go.

**Comment by babichjacob** [comment]
> Looks like `svelte-add` changed what is expected to be defined in an adder: [svelte-add/svelte-add@cd6c1bf](https://github.com/svelte-add/svelte-add/commit/cd6c1bf84b656d941d56a1aa3f04dbd5dd41c30a)

This was a mistake! There weren't supposed to be any changes expected from adders outside `svelte-add`.

Hold tight while I fix this.

**Comment by joshnuss** [comment]
Thanks @babichjacob

**Comment by babichjacob** [comment]
This has been fixed! Sorry it was ever a problem 😦.

**Comment by joshnuss** [comment]
No worries!

Thanks @babichjacob for the fast fix, and for creating svelte-add.
