### ISSUE TITLE
not working with

### ISSUE THREAD

**Issue by schmurfy** [joshnuss/svelte-supabase#5]
I just tried with a newly created app (skeleton app) and I get an error:

```
$ npm init svelte@next myapp
$ cd myapp
$ npm i
$ npx svelte-add joshnuss/svelte-supabase
➕ Svelte Add
The project directory you're giving to this command cannot be guaranteed to be fresh. If any issues arise after running this command, please try again, making sure you've run it on a freshly initialized SvelteKit or Vite–Svelte app template.

joshnuss/svelte-supabase
file:///Users/Schmurfy/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/index.js:310
		reject(new Error(body));
		       ^

Error: command not found: svelte-supabase

    at Socket.<anonymous> (file:///Users/Schmurfy/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/index.js:310:10)
    at Socket.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by joshnuss** [comment]
Hi @schmurfy,

I am unable to reproduce that error.
Works fine for me using the commands you specified.

**Comment by sonya-ninja** [comment]
I get the same error (also a fresh skeleton project):

joshnuss/svelte-supabase
file:///Users/sonya/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/index.js:460
                        reject(new Error(body));
                               ^

Error: [ error ]  An error occured while executing pnpm.
spawn pnpm ENOENT
Error: Command failed with ENOENT: pnpm install
spawn pnpm ENOENT
    at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)
    at onErrorNT (node:internal/child_process:480:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

    at Socket.<anonymous> (file:///Users/sonya/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/index.js:460:11)
    at Socket.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by joshnuss** [comment]
What is your node version and operating system?

**Comment by sonya-ninja** [comment]
> What is your node version and operating system?

Hi Josh!
I'm on mac - 11.4 and Node version: v16.1.0

**Comment by joshnuss** [comment]
Hi @sonya-ninja!

I tried with node v16.1.0 (linux though) and "it worked on my machine" :tm: 

I'm wondering if maybe your `svelte-add` is out of date, can you tell me what version you have?

```bash
cat ~/.npm/_npx/76ab19934dff27c3/node_modules/svelte-add/package.json | grep version
```

**Comment by sonya-ninja** [comment]
Thanks for testing.

"version": "2021.6.3-0.1",
		"package-versions.js",

**Comment by joshnuss** [comment]
Thanks,

I just deployed a fix. Can you confirm it works for you?

Note: the install command changed and I've updated the readme. It is now:

```bash
npx apply joshnuss/supabase
```

**Comment by sonya-ninja** [comment]
Yay!

Success!

Thanks!

[ info ]  Applying preset joshnuss/svelte-supabase.
[ info ]  Installing `@supabase/supabase-js`
[ info ]  Updating environment files...
[ info ]  Updating files...
[ info ]  Extracting templates...
[ success ]  svelte-add/supabase has been applied.

**Comment by joshnuss** [comment]
Awesome! Let me know if you run into anything else,

Thanks @sonya-ninja & @schmurfy for reporting!
