### ISSUE TITLE
Error on install: Host key verification failed.

### ISSUE THREAD

**Issue by mdizo** [joshnuss/svelte-supabase#7]
Trying to run the command `npx apply joshnuss/svelte-supabase` gives me the following error:

```
[ info ]  Applying preset joshnuss/svelte-supabase.
[ error ]  Could not clone joshnuss/svelte-supabase.
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Tested on a new project, Node v16.5.0, running windows 10.

However, running `npx apply https://github.com/joshnuss/svelte-supabase.git` seems to work just fine.

**Comment by joshnuss** [comment]
Hi @mdizo,

It sounds like an issue with ssh.
Are you able to clone this repo with ssh? `git clone git@github.com:joshnuss/svelte-supabase.git`

**Comment by mdizo** [comment]
@joshnuss Thanks for pointing it out, turns out I didn't have SSH configured for my github account. After setting it up I can now successfully clone `git clone git@github.com:joshnuss/svelte-supabase.git`

However running `npx apply joshnuss/svelte-supabase` still gives me an error:
```
[ info ]  Applying preset joshnuss/svelte-supabase.
[ error ]  Access to joshnuss/svelte-supabase denied. If you think it's an error, make sure you
have an SSH key set up and linked to your Git account. If the repository is public and you don't
want to configure SSH, use the --no-ssh flag.
```

Using the `--no-ssh` flag gives me no errors.

**Comment by joshnuss** [comment]
This looks like an error with local ssh configuration. So I'm closing for now.

**Comment by g-gergely** [comment]
> @joshnuss Thanks for pointing it out, turns out I didn't have SSH configured for my github account. After setting it up I can now successfully clone `git clone git@github.com:joshnuss/svelte-supabase.git`
> 
> However running `npx apply joshnuss/svelte-supabase` still gives me an error:
> 
> ```
> [ info ]  Applying preset joshnuss/svelte-supabase.
> [ error ]  Access to joshnuss/svelte-supabase denied. If you think it's an error, make sure you
> have an SSH key set up and linked to your Git account. If the repository is public and you don't
> want to configure SSH, use the --no-ssh flag.
> ```
> 
> Using the `--no-ssh` flag gives me no errors.

I had the same error and your solution worked. Thank you :)
